// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtaebmawwzsmfqlnmpuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0YWVibWF3d3pzbWZxbG5tcHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODk3NTIsImV4cCI6MjA1ODA2NTc1Mn0.hglytHFj-PcmQxJtSjNIFBS3acauOA6CXGX2ymlEBPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);