// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyzmtnnfgrxejiooudwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5em10bm5mZ3J4ZWppb291ZHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjM2ODMsImV4cCI6MjA1NzE5OTY4M30.1sI4wTuPnwRek1Hn3UdBbV_sfIp5EjcSj32WppPTmCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);